# Copyright 2022 Cisco Systems, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index .Values "api-insights" "name" }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ index .Values "api-insights" "labels" }}
spec:
  replicas: {{ index .Values "api-insights" "replicaCount" }}
  selector:
    matchLabels:
      app: {{ index .Values "api-insights" "name" }}
  template:
    metadata:
      labels:
        app: {{ index .Values "api-insights" "name" }}
    spec:
      serviceAccountName: {{ index .Values "api-insights" "serviceAccount" "name" }}
      initContainers:
        - name: '{{ index .Values "api-insights" "name" }}-wait-for-db'
          image: docker.io/bitnami/postgresql:11.13.0-debian-10-r33
          command: ['sh', '-c', 'until pg_isready -h api-insights-{{ index .Values "api-insights" "name" }}-postgresql -p 5432 -U "postgres" -d "dbname={{ index .Values "api-insights-postgresql" "auth" "database" }}";
            do echo waiting for database; sleep 2; done;']
          securityContext:
            runAsUser: 1001
          resources:
          {{- index .Values "api-insights" "initResources" | toYaml | nindent 12 }}
      containers:
        - name: api-insights-ui
          image: '{{ .Values.global.docker.frontendRegistry }}/api-insights-ui:{{ index .Values "api-insights" "docker" "frontendImageTag" }}'
          imagePullPolicy: {{ index .Values "api-insights" "docker" "imagePullPolicy" }}
          env:
            - name: REACT_APP_API_ENDPOINT_URL
              value: "http://localhost:8080"
            - name: BACKEND_API_ENDPOINT_URL
              value: "http://api-insights"
          securityContext:
            {{- index .Values "api-insights" "securityContext" | toYaml | nindent 12 }}
          resources:
            {{- index .Values "api-insights" "resources" | toYaml | nindent 12 }}
        - name: api-insights-api
          image: '{{ .Values.global.docker.backendRegistry }}/api-insights-api:{{ index .Values "api-insights" "docker" "backendImageTag" }}'
          imagePullPolicy: {{ index .Values "api-insights" "docker" "imagePullPolicy" }}
          env:
            - name: API_INSIGHTS_PORT
              value: '8081'
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "api-insights-{{ index .Values "api-insights" "name" }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "api-insights-postgresql" "auth" "existingSecret" }}
                  key: postgres-password
            - name: DB_DATABASE
              value: {{ index .Values "api-insights-postgresql" "auth" "database" }}
            - name: LOG_LEVEL
              value: {{ index .Values "api-insights" "logLevel" }}
            - name: OPENAPI_DIFF_JAR_FILE
              value: /usr/lib/jvm/java-8-openjdk/jre/lib/openapi-diff.jar
            - name: APICLARITY_URL
              value: {{ index .Values "api-insights" "apiclarityUrl" }}
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 15
          securityContext:
            {{- index .Values "api-insights" "securityContext" | toYaml | nindent 12 }}
          resources:
            {{- index .Values "api-insights" "resources" | toYaml | nindent 12 }}
          volumeMounts:
            - name: {{ index .Values "api-insights" "name" }}
              mountPath: {{ index .Values "api-insights" "name" }}
      volumes:
        - name: {{ index .Values "api-insights" "name" }}
          persistentVolumeClaim:
            claimName: {{ index .Values "api-insights" "name" }}-pvc
      securityContext:
        fsGroup: 1000
